# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/vangoghviz',
                'doc_host': 'https://jbwhit.github.io',
                'git_url': 'https://github.com/jbwhit/vangoghviz',
                'lib_path': 'vangoghviz'},
  'syms': {'vangoghviz.core': {'vangoghviz.core.foo': ('core.html#foo', 'vangoghviz/core.py')}}}
